version: "3.9"

services:

  traffic-validation-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: traffic-validation-service
    ports:
      - "7555:7555"
    environment:
      DATABASE_URL: cockroachdb+psycopg://root@cockroachdb:26257/journey_db
      RABBITMQ_URL: amqp://guest:guest@rabbitmq/
      JWT_SECRET: mocksecret
      DEBUG: "true"
